### ISSUE TITLE
SquiDB 2.0 release checklist

### ISSUE THREAD

**Issue by sbosley** [yahoo/squidb#86]
SquiDB 2.0 is nearing completion! This issue will track the final things we need to do before merging the changes into master and releasing new artifacts.

* [x] Unit testing initiative: reduce "unused" method warnings by adding test cases to cover these methods #87 
* [x] Merge dev_2.0 branch into master #90 
* [x] Update wiki pages to reflect new apis/changes
  * [x] Add a "Updating to SquiDB 2.0" doc to the wiki
  * [x] Make sure the README on the front page links to that doc #93 
* [x] Bump version codes in all modules, deploy artifacts, tag in git #93 

SquiDB 2.0 includes the following changes:
* Unified DatabaseDao and AbstractDatabase into a single SquidDatabase API #67
* Basic RxJava support #5, #77 
* Improved data changed notification mechanism #70 
* Support connecting to custom SQLite builds instead of stock Android SQLite #36, #74 
* Enhanced code generation plugin API #32, #83 
* Add SquidRecyclerAdapter for working with RecyclerView #41, #85 
* Other misc fixes and enhancements

**Comment by sbosley** [comment]
SquiDB 2.0 artifacts are now available via jcenter!
